# Generated by Django 5.2.4 on 2025-07-27 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(auto_created=True, default=datetime.date(2025, 7, 28)),
        ),
    ]
